language: node_js
node_js:
  - "8"
dist: trusty
sudo: true

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint # Check quality
  - ng build # Build product
  - xvfb-run ng test --watch=false  # Execute the unit tests via Karma.
  - xvfb-run ng e2e # Execute the end-to-end tests via Protractor.
  
  
after_failure: 
- find /home/travis/.npm/_logs '*.log' -exec cat {} \;
