language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint # Check quality
  - npm run build # Build product
  - xvfb-run npm run test # Execute the unit tests via Karma.
  - xvfb-run npm run e2e # Execute the end-to-end tests via Protractor.
  
  
after_failure: 
- find /home/travis/.npm/_logs '*.log' -exec cat {} \;
